services:
    ubuntu1-service:
        image: ubuntu
        container_name: python
        volumes:
            - /var/www/python:/var/www/python
        working_dir: /var/www/python
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y python3 && sleep infinity"]